package net.disjoint.blocksforbuilders.datagen;

import net.disjoint.blocksforbuilders.BlocksForBuildersBlocks;
import net.disjoint.blocksforbuilders.util.BFBTags;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricTagProvider;
import net.minecraft.registry.RegistryWrapper;
import net.minecraft.registry.tag.BlockTags;

import java.util.concurrent.CompletableFuture;

public class BFBBlockTagProvider extends FabricTagProvider.BlockTagProvider {
    public BFBBlockTagProvider(FabricDataOutput output, CompletableFuture<RegistryWrapper.WrapperLookup> registriesFuture) {
        super(output, registriesFuture);
    }

    @Override
    protected void configure(RegistryWrapper.WrapperLookup wrapperLookup) {
        valueLookupBuilder(BlockTags.AXE_MINEABLE)
                .add(BlocksForBuildersBlocks.BIRCH_BOOKSHELF,
                        BlocksForBuildersBlocks.SPRUCE_BOOKSHELF,
                        BlocksForBuildersBlocks.JUNGLE_BOOKSHELF,
                        BlocksForBuildersBlocks.ACACIA_BOOKSHELF,
                        BlocksForBuildersBlocks.DARK_OAK_BOOKSHELF,
                        BlocksForBuildersBlocks.CRIMSON_BOOKSHELF,
                        BlocksForBuildersBlocks.WARPED_BOOKSHELF,
                        BlocksForBuildersBlocks.MANGROVE_BOOKSHELF,
                        BlocksForBuildersBlocks.CHERRY_BOOKSHELF,
                        BlocksForBuildersBlocks.BAMBOO_BOOKSHELF,
                        BlocksForBuildersBlocks.PALE_OAK_BOOKSHELF,
                        BlocksForBuildersBlocks.GHOSTWOOD_BOOKSHELF,
                        BlocksForBuildersBlocks.SCORCHWOOD_BOOKSHELF,
                        BlocksForBuildersBlocks.GREEN_JUNGLE_BOOKSHELF,
                        BlocksForBuildersBlocks.WILLOW_BOOKSHELF,
                        BlocksForBuildersBlocks.PALM_BOOKSHELF,
                        BlocksForBuildersBlocks.MAPLE_BOOKSHELF,
                        BlocksForBuildersBlocks.BEECH_BOOKSHELF,
                        BlocksForBuildersBlocks.PINE_BOOKSHELF,
                        BlocksForBuildersBlocks.CEDAR_BOOKSHELF,
                        BlocksForBuildersBlocks.GREEN_BAMBOO_BOOKSHELF,
                        BlocksForBuildersBlocks.BAMBOO_THATCH,
                        BlocksForBuildersBlocks.BAMBOO_THATCH_RUG,
                        BlocksForBuildersBlocks.COCONUT_THATCH,
                        BlocksForBuildersBlocks.COCONUT_THATCH_RUG,
                        BlocksForBuildersBlocks.BAMBOO_MOSAIC_RUG);

        valueLookupBuilder(BlockTags.HOE_MINEABLE)
                .add(BlocksForBuildersBlocks.GHOSTWOOD_LEAVES,
                        BlocksForBuildersBlocks.GREEN_JUNGLE_LEAVES,
                        BlocksForBuildersBlocks.WILLOW_LEAVES,
                        BlocksForBuildersBlocks.PALM_LEAVES,
                        BlocksForBuildersBlocks.MAPLE_LEAVES,
                        BlocksForBuildersBlocks.GOLD_ACACIA_LEAVES,
                        BlocksForBuildersBlocks.BEECH_LEAVES,
                        BlocksForBuildersBlocks.PINE_LEAVES,
                        BlocksForBuildersBlocks.CEDAR_LEAVES,
                        BlocksForBuildersBlocks.YELLOW_BIRCH_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_OAK_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_BIRCH_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_SPRUCE_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_JUNGLE_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_ACACIA_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_DARK_OAK_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_AZALEA_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_FLOWERING_AZALEA_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_MANGROVE_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_CHERRY_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_PALE_OAK_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_GHOSTWOOD_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_GREEN_JUNGLE_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_WILLOW_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_PALM_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_MAPLE_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_BEECH_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_PINE_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_CEDAR_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_YELLOW_BIRCH_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_GOLD_ACACIA_LEAVES,
                        BlocksForBuildersBlocks.OAK_HEDGE,
                        BlocksForBuildersBlocks.BIRCH_HEDGE,
                        BlocksForBuildersBlocks.SPRUCE_HEDGE,
                        BlocksForBuildersBlocks.JUNGLE_HEDGE,
                        BlocksForBuildersBlocks.ACACIA_HEDGE,
                        BlocksForBuildersBlocks.DARK_OAK_HEDGE,
                        BlocksForBuildersBlocks.AZALEA_HEDGE,
                        BlocksForBuildersBlocks.FLOWERING_AZALEA_HEDGE,
                        BlocksForBuildersBlocks.MANGROVE_HEDGE,
                        BlocksForBuildersBlocks.CHERRY_HEDGE,
                        BlocksForBuildersBlocks.PALE_OAK_HEDGE,
                        BlocksForBuildersBlocks.GHOSTWOOD_HEDGE,
                        BlocksForBuildersBlocks.GREEN_JUNGLE_HEDGE,
                        BlocksForBuildersBlocks.WILLOW_HEDGE,
                        BlocksForBuildersBlocks.PALM_HEDGE,
                        BlocksForBuildersBlocks.MAPLE_HEDGE,
                        BlocksForBuildersBlocks.BEECH_HEDGE,
                        BlocksForBuildersBlocks.PINE_HEDGE,
                        BlocksForBuildersBlocks.CEDAR_HEDGE,
                        BlocksForBuildersBlocks.YELLOW_BIRCH_HEDGE,
                        BlocksForBuildersBlocks.GOLD_ACACIA_HEDGE,
                        BlocksForBuildersBlocks.ASHEN_CARPET,
                        BlocksForBuildersBlocks.HAY_STAIRS,
                        BlocksForBuildersBlocks.HAY_SLAB,
                        BlocksForBuildersBlocks.HAY_RUG);

        valueLookupBuilder(BlockTags.PICKAXE_MINEABLE)
                .add(BlocksForBuildersBlocks.GRIMSTONE,
                        BlocksForBuildersBlocks.GRIMSTONE_STAIRS,
                        BlocksForBuildersBlocks.GRIMSTONE_SLAB,
                        BlocksForBuildersBlocks.GRIMSTONE_WALL,
                        BlocksForBuildersBlocks.CHISELED_GRIMSTONE,
                        BlocksForBuildersBlocks.POLISHED_GRIMSTONE,
                        BlocksForBuildersBlocks.POLISHED_GRIMSTONE_STAIRS,
                        BlocksForBuildersBlocks.POLISHED_GRIMSTONE_SLAB,
                        BlocksForBuildersBlocks.POLISHED_GRIMSTONE_WALL,
                        BlocksForBuildersBlocks.GRIMSTONE_BRICKS,
                        BlocksForBuildersBlocks.CRACKED_GRIMSTONE_BRICKS,
                        BlocksForBuildersBlocks.GRIMSTONE_BRICK_STAIRS,
                        BlocksForBuildersBlocks.GRIMSTONE_BRICK_SLAB,
                        BlocksForBuildersBlocks.GRIMSTONE_BRICK_WALL,
                        BlocksForBuildersBlocks.GRIMSTONE_TILES,
                        BlocksForBuildersBlocks.CRACKED_GRIMSTONE_TILES,
                        BlocksForBuildersBlocks.GRIMSTONE_TILE_STAIRS,
                        BlocksForBuildersBlocks.GRIMSTONE_TILE_SLAB,
                        BlocksForBuildersBlocks.GRIMSTONE_TILE_WALL,
                        BlocksForBuildersBlocks.ANTIGORITE,
                        BlocksForBuildersBlocks.ANTIGORITE_STAIRS,
                        BlocksForBuildersBlocks.ANTIGORITE_SLAB,
                        BlocksForBuildersBlocks.ANTIGORITE_WALL,
                        BlocksForBuildersBlocks.POLISHED_ANTIGORITE,
                        BlocksForBuildersBlocks.POLISHED_ANTIGORITE_STAIRS,
                        BlocksForBuildersBlocks.POLISHED_ANTIGORITE_SLAB,
                        BlocksForBuildersBlocks.POLISHED_ANTIGORITE_WALL,
                        BlocksForBuildersBlocks.POLISHED_GRANITE_WALL,
                        BlocksForBuildersBlocks.POLISHED_DIORITE_WALL,
                        BlocksForBuildersBlocks.POLISHED_ANDESITE_WALL,
                        BlocksForBuildersBlocks.SMOOTH_STONE_STAIRS,
                        BlocksForBuildersBlocks.SMOOTH_STONE_WALL,
                        BlocksForBuildersBlocks.SMOOTH_STONE_BRICKS,
                        BlocksForBuildersBlocks.CRACKED_SMOOTH_STONE_BRICKS,
                        BlocksForBuildersBlocks.SMOOTH_STONE_BRICK_STAIRS,
                        BlocksForBuildersBlocks.SMOOTH_STONE_BRICK_SLAB,
                        BlocksForBuildersBlocks.SMOOTH_STONE_BRICK_WALL,
                        BlocksForBuildersBlocks.SMOOTH_SANDSTONE_WALL,
                        BlocksForBuildersBlocks.CUT_SANDSTONE_STAIRS,
                        BlocksForBuildersBlocks.CUT_SANDSTONE_WALL,
                        BlocksForBuildersBlocks.SMOOTH_RED_SANDSTONE_WALL,
                        BlocksForBuildersBlocks.CUT_RED_SANDSTONE_STAIRS,
                        BlocksForBuildersBlocks.CUT_RED_SANDSTONE_WALL,
                        BlocksForBuildersBlocks.SANDSTONE_BRICKS,
                        BlocksForBuildersBlocks.CRACKED_SANDSTONE_BRICKS,
                        BlocksForBuildersBlocks.SANDSTONE_BRICK_STAIRS,
                        BlocksForBuildersBlocks.SANDSTONE_BRICK_SLAB,
                        BlocksForBuildersBlocks.SANDSTONE_BRICK_WALL,
                        BlocksForBuildersBlocks.RED_SANDSTONE_BRICKS,
                        BlocksForBuildersBlocks.CRACKED_RED_SANDSTONE_BRICKS,
                        BlocksForBuildersBlocks.RED_SANDSTONE_BRICK_STAIRS,
                        BlocksForBuildersBlocks.RED_SANDSTONE_BRICK_SLAB,
                        BlocksForBuildersBlocks.RED_SANDSTONE_BRICK_WALL,
                        BlocksForBuildersBlocks.BLACK_NETHER_BRICKS,
                        BlocksForBuildersBlocks.CHISELED_BLACK_NETHER_BRICKS,
                        BlocksForBuildersBlocks.CRACKED_BLACK_NETHER_BRICKS,
                        BlocksForBuildersBlocks.BLACK_NETHER_BRICK_STAIRS,
                        BlocksForBuildersBlocks.BLACK_NETHER_BRICK_SLAB,
                        BlocksForBuildersBlocks.BLACK_NETHER_BRICK_WALL,
                        BlocksForBuildersBlocks.BLACK_NETHER_BRICK_FENCE,
                        BlocksForBuildersBlocks.BLACK_NETHER_BRICK_FENCE_GATE,
                        BlocksForBuildersBlocks.CHISELED_RED_NETHER_BRICKS,
                        BlocksForBuildersBlocks.CRACKED_RED_NETHER_BRICKS,
                        BlocksForBuildersBlocks.RED_NETHER_BRICK_FENCE,
                        BlocksForBuildersBlocks.RED_NETHER_BRICK_FENCE_GATE,
                        BlocksForBuildersBlocks.NETHER_BRICK_FENCE_GATE,
                        BlocksForBuildersBlocks.QUARTZ_WALL,
                        BlocksForBuildersBlocks.QUARTZ_BRICK_WALL,
                        BlocksForBuildersBlocks.QUARTZ_BRICK_STAIRS,
                        BlocksForBuildersBlocks.QUARTZ_BRICK_SLAB,
                        BlocksForBuildersBlocks.SMOOTH_QUARTZ_WALL);

        valueLookupBuilder(BlockTags.SHOVEL_MINEABLE)
                .add(BlocksForBuildersBlocks.SCORCHED_GRASS);

        valueLookupBuilder(BlockTags.CEILING_HANGING_SIGNS)
                .add(BlocksForBuildersBlocks.GREEN_JUNGLE_HANGING_SIGN,
                        BlocksForBuildersBlocks.GREEN_BAMBOO_HANGING_SIGN,
                        BlocksForBuildersBlocks.GHOSTWOOD_HANGING_SIGN,
                        BlocksForBuildersBlocks.SCORCHWOOD_HANGING_SIGN,
                        BlocksForBuildersBlocks.WILLOW_HANGING_SIGN,
                        BlocksForBuildersBlocks.PALM_HANGING_SIGN,
                        BlocksForBuildersBlocks.MAPLE_HANGING_SIGN,
                        BlocksForBuildersBlocks.BEECH_HANGING_SIGN,
                        BlocksForBuildersBlocks.PINE_HANGING_SIGN,
                        BlocksForBuildersBlocks.CEDAR_HANGING_SIGN);

        valueLookupBuilder(BlockTags.DOORS)
                .add(BlocksForBuildersBlocks.GREEN_JUNGLE_DOOR,
                        BlocksForBuildersBlocks.GHOSTWOOD_DOOR,
                        BlocksForBuildersBlocks.SCORCHWOOD_DOOR,
                        BlocksForBuildersBlocks.WILLOW_DOOR,
                        BlocksForBuildersBlocks.PALM_DOOR,
                        BlocksForBuildersBlocks.MAPLE_DOOR,
                        BlocksForBuildersBlocks.BEECH_DOOR,
                        BlocksForBuildersBlocks.PINE_DOOR,
                        BlocksForBuildersBlocks.CEDAR_DOOR,
                        BlocksForBuildersBlocks.GREEN_BAMBOO_DOOR);

        valueLookupBuilder(BlockTags.ENCHANTMENT_POWER_PROVIDER)
                .add(BlocksForBuildersBlocks.BIRCH_BOOKSHELF,
                        BlocksForBuildersBlocks.SPRUCE_BOOKSHELF,
                        BlocksForBuildersBlocks.JUNGLE_BOOKSHELF,
                        BlocksForBuildersBlocks.ACACIA_BOOKSHELF,
                        BlocksForBuildersBlocks.DARK_OAK_BOOKSHELF,
                        BlocksForBuildersBlocks.CRIMSON_BOOKSHELF,
                        BlocksForBuildersBlocks.WARPED_BOOKSHELF,
                        BlocksForBuildersBlocks.MANGROVE_BOOKSHELF,
                        BlocksForBuildersBlocks.CHERRY_BOOKSHELF,
                        BlocksForBuildersBlocks.BAMBOO_BOOKSHELF,
                        BlocksForBuildersBlocks.PALE_OAK_BOOKSHELF,
                        BlocksForBuildersBlocks.GHOSTWOOD_BOOKSHELF,
                        BlocksForBuildersBlocks.SCORCHWOOD_BOOKSHELF,
                        BlocksForBuildersBlocks.GREEN_JUNGLE_BOOKSHELF,
                        BlocksForBuildersBlocks.WILLOW_BOOKSHELF,
                        BlocksForBuildersBlocks.PALM_BOOKSHELF,
                        BlocksForBuildersBlocks.MAPLE_BOOKSHELF,
                        BlocksForBuildersBlocks.BEECH_BOOKSHELF,
                        BlocksForBuildersBlocks.PINE_BOOKSHELF,
                        BlocksForBuildersBlocks.CEDAR_BOOKSHELF,
                        BlocksForBuildersBlocks.GREEN_BAMBOO_BOOKSHELF);

        valueLookupBuilder(BlockTags.FENCE_GATES)
                .add(BlocksForBuildersBlocks.GREEN_JUNGLE_FENCE_GATE,
                        BlocksForBuildersBlocks.GHOSTWOOD_FENCE_GATE,
                        BlocksForBuildersBlocks.SCORCHWOOD_FENCE_GATE,
                        BlocksForBuildersBlocks.WILLOW_FENCE_GATE,
                        BlocksForBuildersBlocks.PALM_FENCE_GATE,
                        BlocksForBuildersBlocks.MAPLE_FENCE_GATE,
                        BlocksForBuildersBlocks.BEECH_FENCE_GATE,
                        BlocksForBuildersBlocks.PINE_FENCE_GATE,
                        BlocksForBuildersBlocks.CEDAR_FENCE_GATE,
                        BlocksForBuildersBlocks.GREEN_BAMBOO_FENCE_GATE,
                        BlocksForBuildersBlocks.BLACK_NETHER_BRICK_FENCE_GATE,
                        BlocksForBuildersBlocks.RED_NETHER_BRICK_FENCE_GATE);

        valueLookupBuilder(BlockTags.FENCES)
                .add(BlocksForBuildersBlocks.GHOSTWOOD_FENCE,
                        BlocksForBuildersBlocks.SCORCHWOOD_FENCE,
                        BlocksForBuildersBlocks.GREEN_JUNGLE_FENCE,
                        BlocksForBuildersBlocks.WILLOW_FENCE,
                        BlocksForBuildersBlocks.PALM_FENCE,
                        BlocksForBuildersBlocks.MAPLE_FENCE,
                        BlocksForBuildersBlocks.BEECH_FENCE,
                        BlocksForBuildersBlocks.PINE_FENCE,
                        BlocksForBuildersBlocks.CEDAR_FENCE,
                        BlocksForBuildersBlocks.GREEN_BAMBOO_FENCE,
                        BlocksForBuildersBlocks.BLACK_NETHER_BRICK_FENCE,
                        BlocksForBuildersBlocks.RED_NETHER_BRICK_FENCE);

        valueLookupBuilder(BlockTags.LEAVES)
                .add(BlocksForBuildersBlocks.GREEN_JUNGLE_LEAVES,
                        BlocksForBuildersBlocks.GHOSTWOOD_LEAVES,
                        BlocksForBuildersBlocks.WILLOW_LEAVES,
                        BlocksForBuildersBlocks.PALM_LEAVES,
                        BlocksForBuildersBlocks.MAPLE_LEAVES,
                        BlocksForBuildersBlocks.BEECH_LEAVES,
                        BlocksForBuildersBlocks.PINE_LEAVES,
                        BlocksForBuildersBlocks.CEDAR_LEAVES,
                        BlocksForBuildersBlocks.YELLOW_BIRCH_LEAVES,
                        BlocksForBuildersBlocks.GOLD_ACACIA_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_OAK_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_BIRCH_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_SPRUCE_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_JUNGLE_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_ACACIA_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_DARK_OAK_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_AZALEA_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_FLOWERING_AZALEA_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_MANGROVE_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_CHERRY_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_PALE_OAK_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_GHOSTWOOD_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_GREEN_JUNGLE_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_WILLOW_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_PALM_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_MAPLE_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_GOLD_ACACIA_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_BEECH_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_PINE_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_CEDAR_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_YELLOW_BIRCH_LEAVES,
                        BlocksForBuildersBlocks.OAK_HEDGE,
                        BlocksForBuildersBlocks.BIRCH_HEDGE,
                        BlocksForBuildersBlocks.SPRUCE_HEDGE,
                        BlocksForBuildersBlocks.JUNGLE_HEDGE,
                        BlocksForBuildersBlocks.ACACIA_HEDGE,
                        BlocksForBuildersBlocks.DARK_OAK_HEDGE,
                        BlocksForBuildersBlocks.AZALEA_HEDGE,
                        BlocksForBuildersBlocks.FLOWERING_AZALEA_HEDGE,
                        BlocksForBuildersBlocks.MANGROVE_HEDGE,
                        BlocksForBuildersBlocks.CHERRY_HEDGE,
                        BlocksForBuildersBlocks.PALE_OAK_HEDGE,
                        BlocksForBuildersBlocks.GHOSTWOOD_HEDGE,
                        BlocksForBuildersBlocks.GREEN_JUNGLE_HEDGE,
                        BlocksForBuildersBlocks.WILLOW_HEDGE,
                        BlocksForBuildersBlocks.PALM_HEDGE,
                        BlocksForBuildersBlocks.MAPLE_HEDGE,
                        BlocksForBuildersBlocks.BEECH_HEDGE,
                        BlocksForBuildersBlocks.PINE_HEDGE,
                        BlocksForBuildersBlocks.CEDAR_HEDGE,
                        BlocksForBuildersBlocks.YELLOW_BIRCH_HEDGE,
                        BlocksForBuildersBlocks.GOLD_ACACIA_HEDGE);

        valueLookupBuilder(BlockTags.LOGS_THAT_BURN)
                .addOptionalTag(BFBTags.Blocks.GHOSTWOOD_LOGS)
                .addOptionalTag(BFBTags.Blocks.WILLOW_LOGS)
                .addOptionalTag(BFBTags.Blocks.PALM_LOGS)
                .addOptionalTag(BFBTags.Blocks.MAPLE_LOGS)
                .addOptionalTag(BFBTags.Blocks.BEECH_LOGS)
                .addOptionalTag(BFBTags.Blocks.PINE_LOGS)
                .addOptionalTag(BFBTags.Blocks.CEDAR_LOGS)
                .addOptionalTag(BFBTags.Blocks.GREEN_JUNGLE_LOGS);

        valueLookupBuilder(BlockTags.LOGS)
                .addOptionalTag(BFBTags.Blocks.SCORCHWOOD_LOGS);

        valueLookupBuilder(BFBTags.Blocks.GHOSTWOOD_LOGS)
                .add(BlocksForBuildersBlocks.GHOSTWOOD_LOG,
                        BlocksForBuildersBlocks.GHOSTWOOD_WOOD,
                        BlocksForBuildersBlocks.STRIPPED_GHOSTWOOD_LOG,
                        BlocksForBuildersBlocks.STRIPPED_GHOSTWOOD_WOOD);

        valueLookupBuilder(BFBTags.Blocks.SCORCHWOOD_LOGS)
                .add(BlocksForBuildersBlocks.SCORCHWOOD_LOG,
                        BlocksForBuildersBlocks.SCORCHWOOD_WOOD,
                        BlocksForBuildersBlocks.STRIPPED_SCORCHWOOD_LOG,
                        BlocksForBuildersBlocks.STRIPPED_SCORCHWOOD_WOOD);

        valueLookupBuilder(BFBTags.Blocks.WILLOW_LOGS)
                .add(BlocksForBuildersBlocks.WILLOW_LOG,
                        BlocksForBuildersBlocks.WILLOW_WOOD,
                        BlocksForBuildersBlocks.STRIPPED_WILLOW_LOG,
                        BlocksForBuildersBlocks.STRIPPED_WILLOW_WOOD);

        valueLookupBuilder(BFBTags.Blocks.PALM_LOGS)
                .add(BlocksForBuildersBlocks.PALM_LOG,
                        BlocksForBuildersBlocks.PALM_WOOD,
                        BlocksForBuildersBlocks.STRIPPED_PALM_LOG,
                        BlocksForBuildersBlocks.STRIPPED_PALM_WOOD);

        valueLookupBuilder(BFBTags.Blocks.MAPLE_LOGS)
                .add(BlocksForBuildersBlocks.MAPLE_LOG,
                        BlocksForBuildersBlocks.MAPLE_WOOD,
                        BlocksForBuildersBlocks.STRIPPED_MAPLE_LOG,
                        BlocksForBuildersBlocks.STRIPPED_MAPLE_WOOD);

        valueLookupBuilder(BFBTags.Blocks.BEECH_LOGS)
                .add(BlocksForBuildersBlocks.BEECH_LOG,
                        BlocksForBuildersBlocks.BEECH_WOOD,
                        BlocksForBuildersBlocks.STRIPPED_BEECH_LOG,
                        BlocksForBuildersBlocks.STRIPPED_BEECH_WOOD);

        valueLookupBuilder(BFBTags.Blocks.PINE_LOGS)
                .add(BlocksForBuildersBlocks.PINE_LOG,
                        BlocksForBuildersBlocks.PINE_WOOD,
                        BlocksForBuildersBlocks.STRIPPED_PINE_LOG,
                        BlocksForBuildersBlocks.STRIPPED_PINE_WOOD);

        valueLookupBuilder(BFBTags.Blocks.CEDAR_LOGS)
                .add(BlocksForBuildersBlocks.CEDAR_LOG,
                        BlocksForBuildersBlocks.CEDAR_WOOD,
                        BlocksForBuildersBlocks.STRIPPED_CEDAR_LOG,
                        BlocksForBuildersBlocks.STRIPPED_CEDAR_WOOD);

        valueLookupBuilder(BFBTags.Blocks.GREEN_JUNGLE_LOGS)
                .add(BlocksForBuildersBlocks.GREEN_JUNGLE_LOG,
                        BlocksForBuildersBlocks.GREEN_JUNGLE_WOOD,
                        BlocksForBuildersBlocks.STRIPPED_GREEN_JUNGLE_LOG,
                        BlocksForBuildersBlocks.STRIPPED_GREEN_JUNGLE_WOOD);

        valueLookupBuilder(BlockTags.PLANKS)
                .add(BlocksForBuildersBlocks.GREEN_JUNGLE_PLANKS,
                        BlocksForBuildersBlocks.GHOSTWOOD_PLANKS,
                        BlocksForBuildersBlocks.SCORCHWOOD_PLANKS,
                        BlocksForBuildersBlocks.WILLOW_PLANKS,
                        BlocksForBuildersBlocks.PALM_PLANKS,
                        BlocksForBuildersBlocks.MAPLE_PLANKS,
                        BlocksForBuildersBlocks.BEECH_PLANKS,
                        BlocksForBuildersBlocks.PINE_PLANKS,
                        BlocksForBuildersBlocks.CEDAR_PLANKS,
                        BlocksForBuildersBlocks.GREEN_BAMBOO_PLANKS);

        valueLookupBuilder(BlockTags.SAPLINGS)
                .add(BlocksForBuildersBlocks.GREEN_JUNGLE_SAPLING,
                        BlocksForBuildersBlocks.GHOSTWOOD_SAPLING,
                        BlocksForBuildersBlocks.SCORCHWOOD_SAPLING,
                        BlocksForBuildersBlocks.WILLOW_SAPLING,
                        BlocksForBuildersBlocks.COCONUT,
                        BlocksForBuildersBlocks.MAPLE_SAPLING,
                        BlocksForBuildersBlocks.BEECH_SAPLING,
                        BlocksForBuildersBlocks.PINE_SAPLING,
                        BlocksForBuildersBlocks.CEDAR_SAPLING,
                        BlocksForBuildersBlocks.GOLD_ACACIA_SAPLING,
                        BlocksForBuildersBlocks.YELLOW_BIRCH_SAPLING);

        valueLookupBuilder(BlockTags.SLABS)
                .add(BlocksForBuildersBlocks.GREEN_JUNGLE_SLAB,
                        BlocksForBuildersBlocks.GHOSTWOOD_SLAB,
                        BlocksForBuildersBlocks.SCORCHWOOD_SLAB,
                        BlocksForBuildersBlocks.WILLOW_SLAB,
                        BlocksForBuildersBlocks.PALM_SLAB,
                        BlocksForBuildersBlocks.MAPLE_SLAB,
                        BlocksForBuildersBlocks.BEECH_SLAB,
                        BlocksForBuildersBlocks.PINE_SLAB,
                        BlocksForBuildersBlocks.CEDAR_SLAB,
                        BlocksForBuildersBlocks.GREEN_BAMBOO_SLAB,
                        BlocksForBuildersBlocks.BAMBOO_THATCH_SLAB,
                        BlocksForBuildersBlocks.COCONUT_THATCH_SLAB,
                        BlocksForBuildersBlocks.GRIMSTONE_SLAB,
                        BlocksForBuildersBlocks.POLISHED_GRIMSTONE_SLAB,
                        BlocksForBuildersBlocks.GRIMSTONE_BRICK_SLAB,
                        BlocksForBuildersBlocks.GRIMSTONE_TILE_SLAB,
                        BlocksForBuildersBlocks.ANTIGORITE_SLAB,
                        BlocksForBuildersBlocks.POLISHED_ANTIGORITE_SLAB,
                        BlocksForBuildersBlocks.HAY_SLAB,
                        BlocksForBuildersBlocks.SMOOTH_STONE_BRICK_SLAB,
                        BlocksForBuildersBlocks.SANDSTONE_BRICK_SLAB,
                        BlocksForBuildersBlocks.RED_SANDSTONE_BRICK_SLAB,
                        BlocksForBuildersBlocks.BLACK_NETHER_BRICK_SLAB,
                        BlocksForBuildersBlocks.QUARTZ_BRICK_SLAB);

        valueLookupBuilder(BlockTags.STAIRS)
                .add(BlocksForBuildersBlocks.GREEN_JUNGLE_STAIRS,
                        BlocksForBuildersBlocks.GHOSTWOOD_STAIRS,
                        BlocksForBuildersBlocks.SCORCHWOOD_STAIRS,
                        BlocksForBuildersBlocks.WILLOW_STAIRS,
                        BlocksForBuildersBlocks.PALM_STAIRS,
                        BlocksForBuildersBlocks.MAPLE_STAIRS,
                        BlocksForBuildersBlocks.BEECH_STAIRS,
                        BlocksForBuildersBlocks.PINE_STAIRS,
                        BlocksForBuildersBlocks.CEDAR_STAIRS,
                        BlocksForBuildersBlocks.GREEN_BAMBOO_STAIRS,
                        BlocksForBuildersBlocks.BAMBOO_THATCH_STAIRS,
                        BlocksForBuildersBlocks.COCONUT_THATCH_STAIRS,
                        BlocksForBuildersBlocks.GRIMSTONE_STAIRS,
                        BlocksForBuildersBlocks.GRIMSTONE_STAIRS,
                        BlocksForBuildersBlocks.POLISHED_GRIMSTONE_STAIRS,
                        BlocksForBuildersBlocks.GRIMSTONE_BRICK_STAIRS,
                        BlocksForBuildersBlocks.GRIMSTONE_TILE_STAIRS,
                        BlocksForBuildersBlocks.ANTIGORITE_STAIRS,
                        BlocksForBuildersBlocks.POLISHED_ANTIGORITE_STAIRS,
                        BlocksForBuildersBlocks.HAY_STAIRS,
                        BlocksForBuildersBlocks.SMOOTH_STONE_STAIRS,
                        BlocksForBuildersBlocks.SMOOTH_STONE_BRICK_STAIRS,
                        BlocksForBuildersBlocks.CUT_SANDSTONE_STAIRS,
                        BlocksForBuildersBlocks.CUT_RED_SANDSTONE_STAIRS,
                        BlocksForBuildersBlocks.SANDSTONE_BRICK_STAIRS,
                        BlocksForBuildersBlocks.RED_SANDSTONE_BRICK_STAIRS,
                        BlocksForBuildersBlocks.BLACK_NETHER_BRICK_STAIRS,
                        BlocksForBuildersBlocks.QUARTZ_BRICK_STAIRS);

        valueLookupBuilder(BlockTags.STANDING_SIGNS)
                .add(BlocksForBuildersBlocks.GREEN_JUNGLE_SIGN,
                        BlocksForBuildersBlocks.GHOSTWOOD_SIGN,
                        BlocksForBuildersBlocks.SCORCHWOOD_SIGN,
                        BlocksForBuildersBlocks.WILLOW_SIGN,
                        BlocksForBuildersBlocks.PALM_SIGN,
                        BlocksForBuildersBlocks.MAPLE_SIGN,
                        BlocksForBuildersBlocks.BEECH_SIGN,
                        BlocksForBuildersBlocks.PINE_SIGN,
                        BlocksForBuildersBlocks.CEDAR_SIGN,
                        BlocksForBuildersBlocks.GREEN_BAMBOO_SIGN);

        valueLookupBuilder(BlockTags.TRAPDOORS)
                .add(BlocksForBuildersBlocks.GREEN_JUNGLE_TRAPDOOR,
                        BlocksForBuildersBlocks.GHOSTWOOD_TRAPDOOR,
                        BlocksForBuildersBlocks.SCORCHWOOD_TRAPDOOR,
                        BlocksForBuildersBlocks.WILLOW_TRAPDOOR,
                        BlocksForBuildersBlocks.PALM_TRAPDOOR,
                        BlocksForBuildersBlocks.MAPLE_TRAPDOOR,
                        BlocksForBuildersBlocks.BEECH_TRAPDOOR,
                        BlocksForBuildersBlocks.PINE_TRAPDOOR,
                        BlocksForBuildersBlocks.CEDAR_TRAPDOOR,
                        BlocksForBuildersBlocks.GREEN_BAMBOO_TRAPDOOR);

        valueLookupBuilder(BlockTags.CEILING_HANGING_SIGNS)
                .add(BlocksForBuildersBlocks.GREEN_JUNGLE_HANGING_SIGN,
                        BlocksForBuildersBlocks.GREEN_BAMBOO_HANGING_SIGN,
                        BlocksForBuildersBlocks.GHOSTWOOD_HANGING_SIGN,
                        BlocksForBuildersBlocks.SCORCHWOOD_HANGING_SIGN,
                        BlocksForBuildersBlocks.WILLOW_HANGING_SIGN,
                        BlocksForBuildersBlocks.PALM_HANGING_SIGN,
                        BlocksForBuildersBlocks.MAPLE_HANGING_SIGN,
                        BlocksForBuildersBlocks.BEECH_HANGING_SIGN,
                        BlocksForBuildersBlocks.PINE_HANGING_SIGN,
                        BlocksForBuildersBlocks.CEDAR_HANGING_SIGN);

        valueLookupBuilder(BlockTags.WALL_HANGING_SIGNS)
                .add(BlocksForBuildersBlocks.GREEN_JUNGLE_WALL_HANGING_SIGN,
                        BlocksForBuildersBlocks.GREEN_BAMBOO_WALL_HANGING_SIGN,
                        BlocksForBuildersBlocks.GHOSTWOOD_WALL_HANGING_SIGN,
                        BlocksForBuildersBlocks.SCORCHWOOD_WALL_HANGING_SIGN,
                        BlocksForBuildersBlocks.WILLOW_WALL_HANGING_SIGN,
                        BlocksForBuildersBlocks.PALM_WALL_HANGING_SIGN,
                        BlocksForBuildersBlocks.MAPLE_WALL_HANGING_SIGN,
                        BlocksForBuildersBlocks.BEECH_WALL_HANGING_SIGN,
                        BlocksForBuildersBlocks.PINE_WALL_HANGING_SIGN,
                        BlocksForBuildersBlocks.CEDAR_WALL_HANGING_SIGN);

        valueLookupBuilder(BlockTags.WALL_SIGNS)
                .add(BlocksForBuildersBlocks.GREEN_JUNGLE_WALL_SIGN,
                        BlocksForBuildersBlocks.GHOSTWOOD_WALL_SIGN,
                        BlocksForBuildersBlocks.SCORCHWOOD_WALL_SIGN,
                        BlocksForBuildersBlocks.WILLOW_WALL_SIGN,
                        BlocksForBuildersBlocks.PALM_WALL_SIGN,
                        BlocksForBuildersBlocks.MAPLE_WALL_SIGN,
                        BlocksForBuildersBlocks.BEECH_WALL_SIGN,
                        BlocksForBuildersBlocks.PINE_WALL_SIGN,
                        BlocksForBuildersBlocks.CEDAR_WALL_SIGN,
                        BlocksForBuildersBlocks.GREEN_BAMBOO_WALL_SIGN);

        valueLookupBuilder(BlockTags.WALLS)
                .add(BlocksForBuildersBlocks.GRIMSTONE_WALL,
                        BlocksForBuildersBlocks.POLISHED_GRIMSTONE_WALL,
                        BlocksForBuildersBlocks.GRIMSTONE_BRICK_WALL,
                        BlocksForBuildersBlocks.GRIMSTONE_TILE_WALL,
                        BlocksForBuildersBlocks.ANTIGORITE_WALL,
                        BlocksForBuildersBlocks.POLISHED_ANTIGORITE_WALL,
                        BlocksForBuildersBlocks.POLISHED_GRANITE_WALL,
                        BlocksForBuildersBlocks.POLISHED_DIORITE_WALL,
                        BlocksForBuildersBlocks.POLISHED_ANDESITE_WALL,
                        BlocksForBuildersBlocks.SMOOTH_STONE_WALL,
                        BlocksForBuildersBlocks.SMOOTH_STONE_BRICK_WALL,
                        BlocksForBuildersBlocks.SMOOTH_SANDSTONE_WALL,
                        BlocksForBuildersBlocks.CUT_SANDSTONE_WALL,
                        BlocksForBuildersBlocks.SMOOTH_RED_SANDSTONE_WALL,
                        BlocksForBuildersBlocks.CUT_RED_SANDSTONE_WALL,
                        BlocksForBuildersBlocks.SANDSTONE_BRICK_WALL,
                        BlocksForBuildersBlocks.RED_SANDSTONE_BRICK_WALL,
                        BlocksForBuildersBlocks.BLACK_NETHER_BRICK_WALL,
                        BlocksForBuildersBlocks.QUARTZ_WALL,
                        BlocksForBuildersBlocks.QUARTZ_BRICK_WALL,
                        BlocksForBuildersBlocks.SMOOTH_QUARTZ_WALL,
                        BlocksForBuildersBlocks.OAK_HEDGE,
                        BlocksForBuildersBlocks.BIRCH_HEDGE,
                        BlocksForBuildersBlocks.SPRUCE_HEDGE,
                        BlocksForBuildersBlocks.JUNGLE_HEDGE,
                        BlocksForBuildersBlocks.ACACIA_HEDGE,
                        BlocksForBuildersBlocks.DARK_OAK_HEDGE,
                        BlocksForBuildersBlocks.AZALEA_HEDGE,
                        BlocksForBuildersBlocks.FLOWERING_AZALEA_HEDGE,
                        BlocksForBuildersBlocks.MANGROVE_HEDGE,
                        BlocksForBuildersBlocks.CHERRY_HEDGE,
                        BlocksForBuildersBlocks.PALE_OAK_HEDGE,
                        BlocksForBuildersBlocks.GHOSTWOOD_HEDGE,
                        BlocksForBuildersBlocks.GREEN_JUNGLE_HEDGE,
                        BlocksForBuildersBlocks.WILLOW_HEDGE,
                        BlocksForBuildersBlocks.PALM_HEDGE,
                        BlocksForBuildersBlocks.MAPLE_HEDGE,
                        BlocksForBuildersBlocks.BEECH_HEDGE,
                        BlocksForBuildersBlocks.PINE_HEDGE,
                        BlocksForBuildersBlocks.CEDAR_HEDGE,
                        BlocksForBuildersBlocks.YELLOW_BIRCH_HEDGE,
                        BlocksForBuildersBlocks.GOLD_ACACIA_HEDGE);

        valueLookupBuilder(BlockTags.WOODEN_BUTTONS)
                .add(BlocksForBuildersBlocks.GREEN_JUNGLE_BUTTON,
                        BlocksForBuildersBlocks.GHOSTWOOD_BUTTON,
                        BlocksForBuildersBlocks.SCORCHWOOD_BUTTON,
                        BlocksForBuildersBlocks.WILLOW_BUTTON,
                        BlocksForBuildersBlocks.PALM_BUTTON,
                        BlocksForBuildersBlocks.MAPLE_BUTTON,
                        BlocksForBuildersBlocks.BEECH_BUTTON,
                        BlocksForBuildersBlocks.PINE_BUTTON,
                        BlocksForBuildersBlocks.CEDAR_BUTTON,
                        BlocksForBuildersBlocks.GREEN_BAMBOO_BUTTON);

        valueLookupBuilder(BlockTags.WOODEN_DOORS)
                .add(BlocksForBuildersBlocks.GREEN_JUNGLE_DOOR,
                        BlocksForBuildersBlocks.GHOSTWOOD_DOOR,
                        BlocksForBuildersBlocks.SCORCHWOOD_DOOR,
                        BlocksForBuildersBlocks.WILLOW_DOOR,
                        BlocksForBuildersBlocks.PALM_DOOR,
                        BlocksForBuildersBlocks.MAPLE_DOOR,
                        BlocksForBuildersBlocks.BEECH_DOOR,
                        BlocksForBuildersBlocks.PINE_DOOR,
                        BlocksForBuildersBlocks.CEDAR_DOOR,
                        BlocksForBuildersBlocks.GREEN_BAMBOO_DOOR);

        valueLookupBuilder(BlockTags.WOODEN_FENCES)
                .add(BlocksForBuildersBlocks.GREEN_JUNGLE_FENCE,
                        BlocksForBuildersBlocks.GHOSTWOOD_FENCE,
                        BlocksForBuildersBlocks.SCORCHWOOD_FENCE,
                        BlocksForBuildersBlocks.WILLOW_FENCE,
                        BlocksForBuildersBlocks.PALM_FENCE,
                        BlocksForBuildersBlocks.MAPLE_FENCE,
                        BlocksForBuildersBlocks.BEECH_FENCE,
                        BlocksForBuildersBlocks.PINE_FENCE,
                        BlocksForBuildersBlocks.CEDAR_FENCE,
                        BlocksForBuildersBlocks.GREEN_BAMBOO_FENCE);

        valueLookupBuilder(BlockTags.WOODEN_PRESSURE_PLATES)
                .add(BlocksForBuildersBlocks.GREEN_JUNGLE_PRESSURE_PLATE,
                        BlocksForBuildersBlocks.GHOSTWOOD_PRESSURE_PLATE,
                        BlocksForBuildersBlocks.SCORCHWOOD_PRESSURE_PLATE,
                        BlocksForBuildersBlocks.WILLOW_PRESSURE_PLATE,
                        BlocksForBuildersBlocks.PALM_PRESSURE_PLATE,
                        BlocksForBuildersBlocks.MAPLE_PRESSURE_PLATE,
                        BlocksForBuildersBlocks.BEECH_PRESSURE_PLATE,
                        BlocksForBuildersBlocks.PINE_PRESSURE_PLATE,
                        BlocksForBuildersBlocks.CEDAR_PRESSURE_PLATE,
                        BlocksForBuildersBlocks.GREEN_BAMBOO_PRESSURE_PLATE);

        valueLookupBuilder(BlockTags.WOODEN_SLABS)
                .add(BlocksForBuildersBlocks.GREEN_JUNGLE_SLAB,
                        BlocksForBuildersBlocks.GHOSTWOOD_SLAB,
                        BlocksForBuildersBlocks.SCORCHWOOD_SLAB,
                        BlocksForBuildersBlocks.WILLOW_SLAB,
                        BlocksForBuildersBlocks.PALM_SLAB,
                        BlocksForBuildersBlocks.MAPLE_SLAB,
                        BlocksForBuildersBlocks.BEECH_SLAB,
                        BlocksForBuildersBlocks.PINE_SLAB,
                        BlocksForBuildersBlocks.CEDAR_SLAB,
                        BlocksForBuildersBlocks.GREEN_BAMBOO_SLAB);

        valueLookupBuilder(BlockTags.WOODEN_STAIRS)
                .add(BlocksForBuildersBlocks.GREEN_JUNGLE_STAIRS,
                        BlocksForBuildersBlocks.GHOSTWOOD_STAIRS,
                        BlocksForBuildersBlocks.SCORCHWOOD_STAIRS,
                        BlocksForBuildersBlocks.WILLOW_STAIRS,
                        BlocksForBuildersBlocks.PALM_STAIRS,
                        BlocksForBuildersBlocks.MAPLE_STAIRS,
                        BlocksForBuildersBlocks.BEECH_STAIRS,
                        BlocksForBuildersBlocks.PINE_STAIRS,
                        BlocksForBuildersBlocks.CEDAR_STAIRS,
                        BlocksForBuildersBlocks.GREEN_BAMBOO_STAIRS,
                        BlocksForBuildersBlocks.BAMBOO_THATCH_STAIRS);

        valueLookupBuilder(BlockTags.WOODEN_TRAPDOORS)
                .add(BlocksForBuildersBlocks.GREEN_JUNGLE_TRAPDOOR,
                        BlocksForBuildersBlocks.GHOSTWOOD_TRAPDOOR,
                        BlocksForBuildersBlocks.SCORCHWOOD_TRAPDOOR,
                        BlocksForBuildersBlocks.WILLOW_TRAPDOOR,
                        BlocksForBuildersBlocks.PALM_TRAPDOOR,
                        BlocksForBuildersBlocks.MAPLE_TRAPDOOR,
                        BlocksForBuildersBlocks.BEECH_TRAPDOOR,
                        BlocksForBuildersBlocks.PINE_TRAPDOOR,
                        BlocksForBuildersBlocks.CEDAR_TRAPDOOR,
                        BlocksForBuildersBlocks.GREEN_BAMBOO_TRAPDOOR);

        valueLookupBuilder(BlockTags.JUNGLE_LOGS)
                .addOptionalTag(BFBTags.Blocks.GREEN_JUNGLE_LOGS);

        valueLookupBuilder(BlockTags.INSIDE_STEP_SOUND_BLOCKS)
                .add(BlocksForBuildersBlocks.FALLEN_GHOSTWOOD_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_WILLOW_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_PALM_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_MAPLE_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_GREEN_JUNGLE_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_BEECH_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_PINE_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_CEDAR_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_GOLD_ACACIA_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_YELLOW_BIRCH_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_OAK_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_BIRCH_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_SPRUCE_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_JUNGLE_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_ACACIA_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_DARK_OAK_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_AZALEA_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_FLOWERING_AZALEA_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_MANGROVE_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_CHERRY_LEAVES,
                        BlocksForBuildersBlocks.FALLEN_PALE_OAK_LEAVES,
                        BlocksForBuildersBlocks.HAY_RUG,
                        BlocksForBuildersBlocks.BAMBOO_THATCH_RUG,
                        BlocksForBuildersBlocks.BAMBOO_MOSAIC_RUG,
                        BlocksForBuildersBlocks.COCONUT_THATCH_RUG,
                        BlocksForBuildersBlocks.ASHEN_CARPET);

        valueLookupBuilder(BlockTags.DIRT)
                .add(BlocksForBuildersBlocks.SCORCHED_GRASS);

        valueLookupBuilder(BlockTags.BASE_STONE_OVERWORLD)
                .add(BlocksForBuildersBlocks.ANTIGORITE);

        valueLookupBuilder(BlockTags.STONE_ORE_REPLACEABLES)
                .add(BlocksForBuildersBlocks.ANTIGORITE);
    }
}