package net.disjoint.blocksforbuilders.datagen;

import net.disjoint.blocksforbuilders.CoconutBlock;
import net.disjoint.blocksforbuilders.HedgeBlock;
import net.disjoint.blocksforbuilders.PieBlock;
import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import net.minecraft.block.Block;
import net.minecraft.block.enums.BlockHalf;
import net.minecraft.block.enums.SlabType;
import net.minecraft.block.enums.StairShape;
import net.minecraft.client.data.*;
import net.minecraft.state.property.Properties;
import net.minecraft.util.Identifier;
import net.minecraft.util.math.Direction;

@Environment(EnvType.CLIENT)
public class BFBBlockStateSuppliers {

    public static BlockStateSupplier createHedgeBlockState(Block hedgeBlock, Identifier postId, Identifier singleId, Identifier cornerId, Identifier straightId, Identifier tShapeId, Identifier crossId,
                                                           Identifier tallPostId, Identifier tallSingleId, Identifier tallCornerId, Identifier tallStraightId, Identifier tallTShapeId, Identifier tallCrossId) {
        return VariantsBlockStateSupplier.create(hedgeBlock)
                .coordinate(
                        BlockStateVariantMap.create(HedgeBlock.EAST, HedgeBlock.NORTH, HedgeBlock.SOUTH, HedgeBlock.TALL, HedgeBlock.WEST)
                                .register(false, false, false, false, false,
                                        BlockStateVariant.create().put(VariantSettings.MODEL, postId))
                                .register(false, false, false, true, false,
                                        BlockStateVariant.create().put(VariantSettings.MODEL, tallPostId))
                                .register(false, true, false, false, false,
                                        BlockStateVariant.create().put(VariantSettings.MODEL, singleId))
                                .register(false, true, false, true, false,
                                        BlockStateVariant.create().put(VariantSettings.MODEL, tallSingleId))
                                .register(true, false, false, false, false,
                                        BlockStateVariant.create().put(VariantSettings.MODEL, singleId)
                                                .put(VariantSettings.Y, VariantSettings.Rotation.R90)
                                                .put(VariantSettings.UVLOCK, true))
                                .register(true, false, false, true, false,
                                        BlockStateVariant.create().put(VariantSettings.MODEL, tallSingleId)
                                                .put(VariantSettings.Y, VariantSettings.Rotation.R90)
                                                .put(VariantSettings.UVLOCK, true))
                                .register(false, false, true, false, false,
                                        BlockStateVariant.create().put(VariantSettings.MODEL, singleId)
                                                .put(VariantSettings.Y, VariantSettings.Rotation.R180)
                                                .put(VariantSettings.UVLOCK, true))
                                .register(false, false, true, true, false,
                                        BlockStateVariant.create().put(VariantSettings.MODEL, tallSingleId)
                                                .put(VariantSettings.Y, VariantSettings.Rotation.R180)
                                                .put(VariantSettings.UVLOCK, true))
                                .register(false, false, false, false, true,
                                        BlockStateVariant.create().put(VariantSettings.MODEL, singleId)
                                                .put(VariantSettings.Y, VariantSettings.Rotation.R270)
                                                .put(VariantSettings.UVLOCK, true))
                                .register(false, false, false, true, true,
                                        BlockStateVariant.create().put(VariantSettings.MODEL, tallSingleId)
                                                .put(VariantSettings.Y, VariantSettings.Rotation.R270)
                                                .put(VariantSettings.UVLOCK, true))
                                .register(true, true, false, false, false,
                                        BlockStateVariant.create().put(VariantSettings.MODEL, cornerId))
                                .register(true, true, false, true, false,
                                        BlockStateVariant.create().put(VariantSettings.MODEL, tallCornerId))
                                .register(true, false, true, false, false,
                                        BlockStateVariant.create().put(VariantSettings.MODEL, cornerId)
                                                .put(VariantSettings.Y, VariantSettings.Rotation.R90)
                                                .put(VariantSettings.UVLOCK, true))
                                .register(true, false, true, true, false,
                                        BlockStateVariant.create().put(VariantSettings.MODEL, tallCornerId)
                                                .put(VariantSettings.Y, VariantSettings.Rotation.R90)
                                                .put(VariantSettings.UVLOCK, true))
                                .register(false, false, true, false, true,
                                        BlockStateVariant.create().put(VariantSettings.MODEL, cornerId)
                                                .put(VariantSettings.Y, VariantSettings.Rotation.R180)
                                                .put(VariantSettings.UVLOCK, true))
                                .register(false, false, true, true, true,
                                        BlockStateVariant.create().put(VariantSettings.MODEL, tallCornerId)
                                                .put(VariantSettings.Y, VariantSettings.Rotation.R180)
                                                .put(VariantSettings.UVLOCK, true))
                                .register(false, true, false, false, true,
                                        BlockStateVariant.create().put(VariantSettings.MODEL, cornerId)
                                                .put(VariantSettings.Y, VariantSettings.Rotation.R270)
                                                .put(VariantSettings.UVLOCK, true))
                                .register(false, true, false, true, true,
                                        BlockStateVariant.create().put(VariantSettings.MODEL, tallCornerId)
                                                .put(VariantSettings.Y, VariantSettings.Rotation.R270)
                                                .put(VariantSettings.UVLOCK, true))
                                .register(false, true, true, false, false,
                                        BlockStateVariant.create().put(VariantSettings.MODEL, straightId))
                                .register(false, true, true, true, false,
                                        BlockStateVariant.create().put(VariantSettings.MODEL, tallStraightId))
                                .register(true, false, false, false, true,
                                        BlockStateVariant.create().put(VariantSettings.MODEL, straightId)
                                                .put(VariantSettings.Y, VariantSettings.Rotation.R90)
                                                .put(VariantSettings.UVLOCK, true))
                                .register(true, false, false, true, true,
                                        BlockStateVariant.create().put(VariantSettings.MODEL, tallStraightId)
                                                .put(VariantSettings.Y, VariantSettings.Rotation.R90)
                                                .put(VariantSettings.UVLOCK, true))
                                .register(true, true, true, false, false,
                                        BlockStateVariant.create().put(VariantSettings.MODEL, tShapeId))
                                .register(true, true, true, true, false,
                                        BlockStateVariant.create().put(VariantSettings.MODEL, tallTShapeId))
                                .register(true, false, true, false, true,
                                        BlockStateVariant.create().put(VariantSettings.MODEL, tShapeId)
                                                .put(VariantSettings.Y, VariantSettings.Rotation.R90)
                                                .put(VariantSettings.UVLOCK, true))
                                .register(true, false, true, true, true,
                                        BlockStateVariant.create().put(VariantSettings.MODEL, tallTShapeId)
                                                .put(VariantSettings.Y, VariantSettings.Rotation.R90)
                                                .put(VariantSettings.UVLOCK, true))
                                .register(false, true, true, false, true,
                                        BlockStateVariant.create().put(VariantSettings.MODEL, tShapeId)
                                                .put(VariantSettings.Y, VariantSettings.Rotation.R180)
                                                .put(VariantSettings.UVLOCK, true))
                                .register(false, true, true, true, true,
                                        BlockStateVariant.create().put(VariantSettings.MODEL, tallTShapeId)
                                                .put(VariantSettings.Y, VariantSettings.Rotation.R180)
                                                .put(VariantSettings.UVLOCK, true))
                                .register(true, true, false, false, true,
                                        BlockStateVariant.create().put(VariantSettings.MODEL, tShapeId)
                                                .put(VariantSettings.Y, VariantSettings.Rotation.R270)
                                                .put(VariantSettings.UVLOCK, true))
                                .register(true, true, false, true, true,
                                        BlockStateVariant.create().put(VariantSettings.MODEL, tallTShapeId)
                                                .put(VariantSettings.Y, VariantSettings.Rotation.R270)
                                                .put(VariantSettings.UVLOCK, true))
                                .register(true, true, true, false, true,
                                        BlockStateVariant.create().put(VariantSettings.MODEL, crossId))
                                .register(true, true, true, true, true,
                                        BlockStateVariant.create().put(VariantSettings.MODEL, tallCrossId))
                );
    }

    public static BlockStateSupplier createDirectionalStairsBlockState(Block block, Identifier straight, Identifier innerLeft, Identifier innerRight, Identifier outerLeft, Identifier outerRight) {
        return VariantsBlockStateSupplier.create(block)
                .coordinate(
                        BlockStateVariantMap.create(Properties.HORIZONTAL_FACING, Properties.BLOCK_HALF, Properties.STAIR_SHAPE)
                                .register(Direction.EAST, BlockHalf.BOTTOM, StairShape.STRAIGHT, BlockStateVariant.create().put(VariantSettings.MODEL, straight))
                                .register(
                                        Direction.WEST, BlockHalf.BOTTOM, StairShape.STRAIGHT, BlockStateVariant.create()
                                                .put(VariantSettings.MODEL, straight)
                                                .put(VariantSettings.Y, VariantSettings.Rotation.R180)
                                                .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.SOUTH, BlockHalf.BOTTOM, StairShape.STRAIGHT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, straight)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R90)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.NORTH, BlockHalf.BOTTOM, StairShape.STRAIGHT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, straight)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R270)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.EAST, BlockHalf.BOTTOM, StairShape.OUTER_RIGHT, BlockStateVariant.create().put(VariantSettings.MODEL, outerRight))
                                .register(Direction.WEST, BlockHalf.BOTTOM, StairShape.OUTER_RIGHT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, outerRight)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.SOUTH, BlockHalf.BOTTOM, StairShape.OUTER_RIGHT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, outerRight)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R90)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.NORTH, BlockHalf.BOTTOM, StairShape.OUTER_RIGHT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, outerRight)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R270)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.EAST, BlockHalf.BOTTOM, StairShape.OUTER_LEFT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, outerLeft)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R270)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.WEST, BlockHalf.BOTTOM, StairShape.OUTER_LEFT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, outerLeft)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R90)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.SOUTH, BlockHalf.BOTTOM, StairShape.OUTER_LEFT, BlockStateVariant.create().put(VariantSettings.MODEL, outerLeft))
                                .register(Direction.NORTH, BlockHalf.BOTTOM, StairShape.OUTER_LEFT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, outerLeft)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.EAST, BlockHalf.BOTTOM, StairShape.INNER_RIGHT, BlockStateVariant.create().put(VariantSettings.MODEL, innerRight))
                                .register(Direction.WEST, BlockHalf.BOTTOM, StairShape.INNER_RIGHT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, innerRight)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.SOUTH, BlockHalf.BOTTOM, StairShape.INNER_RIGHT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, innerRight)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R90)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.NORTH, BlockHalf.BOTTOM, StairShape.INNER_RIGHT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, innerRight)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R270)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.EAST, BlockHalf.BOTTOM, StairShape.INNER_LEFT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, innerLeft)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R270)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.WEST, BlockHalf.BOTTOM, StairShape.INNER_LEFT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, innerLeft)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R90)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.SOUTH, BlockHalf.BOTTOM, StairShape.INNER_LEFT, BlockStateVariant.create().put(VariantSettings.MODEL, innerLeft))
                                .register(Direction.NORTH, BlockHalf.BOTTOM, StairShape.INNER_LEFT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, innerLeft)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.EAST, BlockHalf.TOP, StairShape.STRAIGHT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, straight)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.WEST, BlockHalf.TOP, StairShape.STRAIGHT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, straight)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.SOUTH, BlockHalf.TOP, StairShape.STRAIGHT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, straight)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R90)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.NORTH, BlockHalf.TOP, StairShape.STRAIGHT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, straight)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R270)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.EAST, BlockHalf.TOP, StairShape.OUTER_RIGHT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, outerRight)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R90)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.WEST, BlockHalf.TOP, StairShape.OUTER_RIGHT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, outerRight)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R270)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.SOUTH, BlockHalf.TOP, StairShape.OUTER_RIGHT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, outerRight)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.NORTH, BlockHalf.TOP, StairShape.OUTER_RIGHT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, outerRight)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.EAST, BlockHalf.TOP, StairShape.OUTER_LEFT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, outerLeft)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.WEST, BlockHalf.TOP, StairShape.OUTER_LEFT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, outerLeft)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.SOUTH, BlockHalf.TOP, StairShape.OUTER_LEFT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, outerLeft)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R90)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.NORTH, BlockHalf.TOP, StairShape.OUTER_LEFT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, outerLeft)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R270)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.EAST, BlockHalf.TOP, StairShape.INNER_RIGHT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, innerRight)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R90)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.WEST, BlockHalf.TOP, StairShape.INNER_RIGHT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, innerRight)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R270)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.SOUTH, BlockHalf.TOP, StairShape.INNER_RIGHT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, innerRight)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.NORTH, BlockHalf.TOP, StairShape.INNER_RIGHT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, innerRight)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.EAST, BlockHalf.TOP, StairShape.INNER_LEFT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, innerLeft)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.WEST, BlockHalf.TOP, StairShape.INNER_LEFT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, innerLeft)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.SOUTH, BlockHalf.TOP, StairShape.INNER_LEFT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, innerLeft)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R90)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.NORTH, BlockHalf.TOP, StairShape.INNER_LEFT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, innerLeft)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R270)
                                        .put(VariantSettings.UVLOCK, false)
                                ));
    }

    public static BlockStateSupplier createDirectionalSlabBlockState(Block block, Identifier slab, Identifier topSlab, Identifier doubleBlock) {
        return VariantsBlockStateSupplier.create(block)
                .coordinate(
                        BlockStateVariantMap.create(Properties.HORIZONTAL_FACING, Properties.SLAB_TYPE)
                                .register(Direction.EAST, SlabType.BOTTOM, BlockStateVariant.create().put(VariantSettings.MODEL, slab)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R270)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.EAST, SlabType.DOUBLE, BlockStateVariant.create().put(VariantSettings.MODEL, doubleBlock)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R270)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.EAST, SlabType.TOP, BlockStateVariant.create().put(VariantSettings.MODEL, topSlab)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R270)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.NORTH, SlabType.BOTTOM, BlockStateVariant.create().put(VariantSettings.MODEL, slab)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.NORTH, SlabType.DOUBLE, BlockStateVariant.create().put(VariantSettings.MODEL, doubleBlock)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.NORTH, SlabType.TOP, BlockStateVariant.create().put(VariantSettings.MODEL, topSlab)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.SOUTH, SlabType.BOTTOM, BlockStateVariant.create().put(VariantSettings.MODEL, slab)
                                )
                                .register(Direction.SOUTH, SlabType.DOUBLE, BlockStateVariant.create().put(VariantSettings.MODEL, doubleBlock)
                                )
                                .register(Direction.SOUTH, SlabType.TOP, BlockStateVariant.create().put(VariantSettings.MODEL, topSlab)
                                )
                                .register(Direction.WEST, SlabType.BOTTOM, BlockStateVariant.create().put(VariantSettings.MODEL, slab)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R90)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.WEST, SlabType.DOUBLE, BlockStateVariant.create().put(VariantSettings.MODEL, doubleBlock)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R90)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.WEST, SlabType.TOP, BlockStateVariant.create().put(VariantSettings.MODEL, topSlab)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R90)
                                        .put(VariantSettings.UVLOCK, false)
                                ));
    }

    public static BlockStateSupplier createPillarSlabBlockState(Block block, Identifier slab, Identifier topSlab, Identifier yAxisSlab, Identifier yAxisTopSlab, Identifier doubleBlock) {
        return VariantsBlockStateSupplier.create(block)
                .coordinate(
                        BlockStateVariantMap.create(Properties.FACING, Properties.SLAB_TYPE)
                                .register(Direction.EAST, SlabType.BOTTOM, BlockStateVariant.create().put(VariantSettings.MODEL, slab)
                                )
                                .register(Direction.EAST, SlabType.DOUBLE, BlockStateVariant.create().put(VariantSettings.MODEL, doubleBlock)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R270)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R90)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.EAST, SlabType.TOP, BlockStateVariant.create().put(VariantSettings.MODEL, topSlab)
                                )
                                .register(Direction.NORTH, SlabType.BOTTOM, BlockStateVariant.create().put(VariantSettings.MODEL, slab)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R270)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.NORTH, SlabType.DOUBLE, BlockStateVariant.create().put(VariantSettings.MODEL, doubleBlock)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R270)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.NORTH, SlabType.TOP, BlockStateVariant.create().put(VariantSettings.MODEL, topSlab)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R270)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.SOUTH, SlabType.BOTTOM, BlockStateVariant.create().put(VariantSettings.MODEL, slab)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R90)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.SOUTH, SlabType.DOUBLE, BlockStateVariant.create().put(VariantSettings.MODEL, doubleBlock)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R270)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.SOUTH, SlabType.TOP, BlockStateVariant.create().put(VariantSettings.MODEL, topSlab)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R90)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.WEST, SlabType.BOTTOM, BlockStateVariant.create().put(VariantSettings.MODEL, slab)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.WEST, SlabType.DOUBLE, BlockStateVariant.create().put(VariantSettings.MODEL, doubleBlock)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R270)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R90)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.WEST, SlabType.TOP, BlockStateVariant.create().put(VariantSettings.MODEL, topSlab)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.UP, SlabType.BOTTOM, BlockStateVariant.create().put(VariantSettings.MODEL, yAxisSlab)
                                )
                                .register(Direction.UP, SlabType.DOUBLE, BlockStateVariant.create().put(VariantSettings.MODEL, doubleBlock)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.UP, SlabType.TOP, BlockStateVariant.create().put(VariantSettings.MODEL, yAxisTopSlab)
                                )
                                .register(Direction.DOWN, SlabType.BOTTOM, BlockStateVariant.create().put(VariantSettings.MODEL, yAxisTopSlab)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.DOWN, SlabType.DOUBLE, BlockStateVariant.create().put(VariantSettings.MODEL, doubleBlock)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.DOWN, SlabType.TOP, BlockStateVariant.create().put(VariantSettings.MODEL, yAxisSlab)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.UVLOCK, false)
                                ));
    }

    public static BlockStateSupplier createPillarCarpetBlockState(Block block, Identifier carpet) {
        return VariantsBlockStateSupplier.create(block)
                .coordinate(
                        BlockStateVariantMap.create(Properties.HORIZONTAL_FACING)
                                .register(Direction.EAST, BlockStateVariant.create().put(VariantSettings.MODEL, carpet)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.NORTH, BlockStateVariant.create().put(VariantSettings.MODEL, carpet)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R90)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.SOUTH, BlockStateVariant.create().put(VariantSettings.MODEL, carpet)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R270)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.WEST, BlockStateVariant.create().put(VariantSettings.MODEL, carpet)
                                ));
    }

    public static BlockStateSupplier createDirectionalBlockState(Block block, Identifier model) {
        return VariantsBlockStateSupplier.create(block)
                .coordinate(
                        BlockStateVariantMap.create(Properties.FACING)
                                .register(Direction.DOWN, BlockStateVariant.create().put(VariantSettings.MODEL, model)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.EAST, BlockStateVariant.create().put(VariantSettings.MODEL, model)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R90)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R90)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.NORTH, BlockStateVariant.create().put(VariantSettings.MODEL, model)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R90)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.SOUTH, BlockStateVariant.create().put(VariantSettings.MODEL, model)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R90)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.UP, BlockStateVariant.create().put(VariantSettings.MODEL, model))
                                .register(Direction.WEST, BlockStateVariant.create().put(VariantSettings.MODEL, model)
                                                .put(VariantSettings.X, VariantSettings.Rotation.R90)
                                                .put(VariantSettings.Y, VariantSettings.Rotation.R270)
                                                .put(VariantSettings.UVLOCK, false)
                                ));
    }

    public static BlockStateSupplier createGrimstoneStyleStairsBlockState(Block block, Identifier straight, Identifier straightTop, Identifier inner, Identifier innerTop, Identifier outer, Identifier outerTop) {
        return VariantsBlockStateSupplier.create(block)
                .coordinate(
                        BlockStateVariantMap.create(Properties.HORIZONTAL_FACING, Properties.BLOCK_HALF, Properties.STAIR_SHAPE)
                                .register(Direction.EAST, BlockHalf.BOTTOM, StairShape.STRAIGHT, BlockStateVariant.create().put(VariantSettings.MODEL, straight))
                                .register(
                                        Direction.WEST, BlockHalf.BOTTOM, StairShape.STRAIGHT, BlockStateVariant.create()
                                                .put(VariantSettings.MODEL, straight)
                                                .put(VariantSettings.Y, VariantSettings.Rotation.R180)
                                                .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.SOUTH, BlockHalf.BOTTOM, StairShape.STRAIGHT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, straight)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R90)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.NORTH, BlockHalf.BOTTOM, StairShape.STRAIGHT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, straight)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R270)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.EAST, BlockHalf.BOTTOM, StairShape.OUTER_RIGHT, BlockStateVariant.create().put(VariantSettings.MODEL, outer))
                                .register(Direction.WEST, BlockHalf.BOTTOM, StairShape.OUTER_RIGHT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, outer)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.SOUTH, BlockHalf.BOTTOM, StairShape.OUTER_RIGHT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, outer)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R90)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.NORTH, BlockHalf.BOTTOM, StairShape.OUTER_RIGHT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, outer)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R270)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.EAST, BlockHalf.BOTTOM, StairShape.OUTER_LEFT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, outer)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R270)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.WEST, BlockHalf.BOTTOM, StairShape.OUTER_LEFT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, outer)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R90)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.SOUTH, BlockHalf.BOTTOM, StairShape.OUTER_LEFT, BlockStateVariant.create().put(VariantSettings.MODEL, outer))
                                .register(Direction.NORTH, BlockHalf.BOTTOM, StairShape.OUTER_LEFT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, outer)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.EAST, BlockHalf.BOTTOM, StairShape.INNER_RIGHT, BlockStateVariant.create().put(VariantSettings.MODEL, inner))
                                .register(Direction.WEST, BlockHalf.BOTTOM, StairShape.INNER_RIGHT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, inner)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.SOUTH, BlockHalf.BOTTOM, StairShape.INNER_RIGHT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, inner)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R90)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.NORTH, BlockHalf.BOTTOM, StairShape.INNER_RIGHT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, inner)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R270)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.EAST, BlockHalf.BOTTOM, StairShape.INNER_LEFT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, inner)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R270)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.WEST, BlockHalf.BOTTOM, StairShape.INNER_LEFT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, inner)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R90)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.SOUTH, BlockHalf.BOTTOM, StairShape.INNER_LEFT, BlockStateVariant.create().put(VariantSettings.MODEL, inner))
                                .register(Direction.NORTH, BlockHalf.BOTTOM, StairShape.INNER_LEFT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, inner)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.EAST, BlockHalf.TOP, StairShape.STRAIGHT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, straightTop)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.WEST, BlockHalf.TOP, StairShape.STRAIGHT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, straightTop)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.SOUTH, BlockHalf.TOP, StairShape.STRAIGHT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, straightTop)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R90)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.NORTH, BlockHalf.TOP, StairShape.STRAIGHT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, straightTop)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R270)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.EAST, BlockHalf.TOP, StairShape.OUTER_RIGHT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, outerTop)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R90)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.WEST, BlockHalf.TOP, StairShape.OUTER_RIGHT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, outerTop)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R270)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.SOUTH, BlockHalf.TOP, StairShape.OUTER_RIGHT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, outerTop)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.NORTH, BlockHalf.TOP, StairShape.OUTER_RIGHT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, outerTop)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.EAST, BlockHalf.TOP, StairShape.OUTER_LEFT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, outerTop)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.WEST, BlockHalf.TOP, StairShape.OUTER_LEFT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, outerTop)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.SOUTH, BlockHalf.TOP, StairShape.OUTER_LEFT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, outerTop)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R90)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.NORTH, BlockHalf.TOP, StairShape.OUTER_LEFT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, outerTop)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R270)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.EAST, BlockHalf.TOP, StairShape.INNER_RIGHT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, innerTop)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R90)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.WEST, BlockHalf.TOP, StairShape.INNER_RIGHT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, innerTop)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R270)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.SOUTH, BlockHalf.TOP, StairShape.INNER_RIGHT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, innerTop)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.NORTH, BlockHalf.TOP, StairShape.INNER_RIGHT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, innerTop)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.EAST, BlockHalf.TOP, StairShape.INNER_LEFT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, innerTop)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.WEST, BlockHalf.TOP, StairShape.INNER_LEFT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, innerTop)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.SOUTH, BlockHalf.TOP, StairShape.INNER_LEFT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, innerTop)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R90)
                                        .put(VariantSettings.UVLOCK, false)
                                )
                                .register(Direction.NORTH, BlockHalf.TOP, StairShape.INNER_LEFT, BlockStateVariant.create()
                                        .put(VariantSettings.MODEL, innerTop)
                                        .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                        .put(VariantSettings.Y, VariantSettings.Rotation.R270)
                                        .put(VariantSettings.UVLOCK, false)
                                ));
    }

    public static BlockStateSupplier createPieBlockState(Block block, Identifier full, Identifier oneBite, Identifier twoBites, Identifier threeBites) {
        return VariantsBlockStateSupplier.create(block)
                .coordinate(
                        BlockStateVariantMap.create(PieBlock.CHOMPS)
                                .register(0, BlockStateVariant.create().put(VariantSettings.MODEL, full)
                                )
                                .register(1, BlockStateVariant.create().put(VariantSettings.MODEL, oneBite)
                                )
                                .register(2, BlockStateVariant.create().put(VariantSettings.MODEL, twoBites)
                                )
                                .register(3, BlockStateVariant.create().put(VariantSettings.MODEL, threeBites)
                                ));
    }

    public static BlockStateSupplier createCoconutBlockState(Block block, Identifier identifier, Identifier strippedId, Identifier emptyId, Identifier strippedEmptyId) {
        return VariantsBlockStateSupplier.create(block)
                .coordinate(
                        BlockStateVariantMap.create(CoconutBlock.HANGING, CoconutBlock.HAS_FIBER, CoconutBlock.HAS_MILK)
                                .register(false, true, true,
                                        BlockStateVariant.create().put(VariantSettings.MODEL, identifier))
                                .register(true, true, true,
                                        BlockStateVariant.create().put(VariantSettings.MODEL, identifier)
                                                .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                                .put(VariantSettings.UVLOCK, false))
                                .register(false, true, false,
                                        BlockStateVariant.create().put(VariantSettings.MODEL, emptyId))
                                .register(true, true, false,
                                        BlockStateVariant.create().put(VariantSettings.MODEL, emptyId)
                                                .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                                .put(VariantSettings.UVLOCK, false))
                                .register(false, false, true,
                                        BlockStateVariant.create().put(VariantSettings.MODEL, strippedId))
                                .register(true, false, true,
                                        BlockStateVariant.create().put(VariantSettings.MODEL, strippedId)
                                                .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                                .put(VariantSettings.UVLOCK, false))
                                .register(false, false, false,
                                        BlockStateVariant.create().put(VariantSettings.MODEL, strippedEmptyId))
                                .register(true, false, false,
                                        BlockStateVariant.create().put(VariantSettings.MODEL, strippedEmptyId)
                                                .put(VariantSettings.X, VariantSettings.Rotation.R180)
                                                .put(VariantSettings.UVLOCK, false)
                ));
    }

}
